### ISSUE TITLE
links for the polyphonic music datasets broken

### ISSUE THREAD

**Issue by hyunjik11** [harvardnlp/TextFlow#3]
It seems like the following links are broken:
https://d2fefpcigoriu7.cloudfront.net/datasets/polyphonic/jsb_chorales.pickle
https://d2fefpcigoriu7.cloudfront.net/datasets/polyphonic/piano_midi.pickle
https://d2fefpcigoriu7.cloudfront.net/datasets/polyphonic/muse_data.pickle
https://d2fefpcigoriu7.cloudfront.net/datasets/polyphonic/nottingham.pickle

Should they be modified to:
http://www-etud.iro.umontreal.ca/~boulanni/JSB%20Chorales.pickle
http://www-etud.iro.umontreal.ca/~boulanni/Piano-midi.de.pickle
http://www-etud.iro.umontreal.ca/~boulanni/MuseData.pickle
http://www-etud.iro.umontreal.ca/~boulanni/Nottingham.pickle

**Comment by zackziegler95** [comment]
Yes, you are right, it seems like whoever was previously hosting the data stopped. Thanks for finding the other links, I've updated them on master and I believe they should be identical.
